version: '3.7'

services:
  django:
    build: .
    container_name: django
    command: bash -c "python manage.py fill_db && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - minio

  minio:
    hostname: minio/minio:latest
    image: quay.io/minio/minio:RELEASE.2022-10-15T19-57-03Z
    container_name: minio
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    expose:
      - "9000"
      - "9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio-data:/data

  createbucket:
    image: minio/mc:latest
    container_name: createbucket
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add --api s3v4 s3 http://minio:9000 minio minio123;
      /usr/bin/mc mb s3/images;
      /usr/bin/mc anonymous set public s3/images;
      "
      
  nginx:
    image: nginx:1.19.2-alpine
    container_name: nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio

volumes:
  minio-data: